{
  "comments": [
    {
      "key": {
        "uuid": "c74e1982_e8c84b9c",
        "filename": "src/com/android/mms/data/Contact.java",
        "patchSetId": 1
      },
      "lineNbr": 359,
      "author": {
        "id": 1024767
      },
      "writtenOn": "2013-09-09T16:49:43Z",
      "side": 1,
      "message": "wonder if you should be doing a join on the thread after the interrupt.  otherwise I\u0027m not sure there are any guarantees that the other thread has received the interrupt exception.  perhaps it doesn\u0027t matter in this case.  I wasn\u0027t sure if this was a correctness issue or a perf issue or something else.",
      "revId": "8695bcf0a94f1a4a072e3fd03df4260a54f4c8f5",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "c74e1982_88cf97a0",
        "filename": "src/com/android/mms/data/Contact.java",
        "patchSetId": 1
      },
      "lineNbr": 509,
      "author": {
        "id": 1024767
      },
      "writtenOn": "2013-09-09T16:49:43Z",
      "side": 1,
      "message": "should we move the catch to a higher level?  it seems like we\u0027ll get the interrupted exception but then just continue (while true).  maybe I\u0027m not understanding how this code works in it\u0027s entirety.",
      "revId": "8695bcf0a94f1a4a072e3fd03df4260a54f4c8f5",
      "serverId": "85c56323-6fa9-3386-8a01-6480fb634889",
      "unresolved": false
    }
  ]
}